### ISSUE TITLE
Problem with non-existing pathLinkFolder

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#19]
I've been making new installation and found this little problem (maybe confusing for new user, got even myself stuck for a moment).

1. I've install **linvstmanager**
2. Copied my `linvstmanager_config.xml`, which has
```
<pathLinkFolder>/home/x133/.vst</pathLinkFolder>
```
3. Selected **Mismatch** in right filter panel
4. Updated them all (successfull)
5. Selected **Disabled** in right filter panel
6. Tired to **Enable** them all and got completely stuck (nothing happens, nothing moves, no errors / warnings)

Obviously that was problem of not actually having **~/.vst** in a first place, creating it and trying again have fixed "problem" :laughing: 

There are two ways to be nicer here:
1. Auto-create folder written at config's **pathLinkFolder**
2. Give warning / error in that case, so user wouldn't scratch head too much :smile:

**Comment by Goli4thus** [comment]
Alright, that's a new usecase, but still a valid scenario that could happen to people upgrading their system.
Added a check during startup (417c03d0517e4879a080c7fdd17c2b56e22b35c4). If the link folder is specified in config file, but doesn't exist, it will be created as an empty folder.

So that would be your option 1. I think that one is the nicer user experience.
Regarding option 2: So far I only warn in that case (not being able to "enable") with a debug message.
But one only gets that with a debug build (some time ago I think I mentioned somewhere on how to enable that with cmake).

**Comment by keybreak** [comment]
> So that would be your option 1. I think that one is the nicer user experience.

Yeah, i agree :+1: 

Tested, works as expected!
