### ISSUE TITLE
UI text truncationless, possible areas for improvements

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#20]
We've discussed it during testing period a little, since then i've moved from Manjaro Deepin to Manjaro KDE, although i use same font of **Noto Sans 10pt** systemwide, my monitor have somewhat odd 101x101 dpi with 2560x1600 resolution, so fonts render little bigger by OS, than usual setups...

![Screenshot_20200725_004216](https://user-images.githubusercontent.com/47599989/88437962-47587700-ce10-11ea-9943-90e3fed06ded.png)

Problematic areas currently:
1. **Status** column, maybe it's better to use some auto value so it would set width by value of widest element in column (if qt have it, i'm thinking web-like tables).

2. **Filters** right panel, obviously using fixed width panel here will lead to stuff like that, on some monitors and / or bigger font-sizes

____________

P.S. Btw, just in case, **linvstmanager** uses proper System settings fonts, not stuff like **fontconfig** defaults, right?
```
fc-match Sans
fc-match Seriff
fc-match Mono
```

**Comment by Goli4thus** [comment]
Regarding "status column":
Turns out I already did auto resize all columns. But for whatever reason I thought previously I can do better than auto resize and make it extra neatly resized.
Guess I completely ignored that with other fonts on other systems it might look quite different.

So now with the change in 827a25bc9e4bb7a2134ce71632437bcb354dad4b, it auto scales basically everything. Exceptiong are the first column and some columns that get even more width to make it look nicer.

Regarding "filters" (or sidebar):
That one isn't that easy to fix after all. I did a bit of minor resizing (3fc262573f4a73b945b118c4998fb8aea6c825e5), but that's not really a fix. I guess here I missed as well that other systems with other font settings might look quite different.

Looks to me that I'd basically would have to rewrite big chunks of that sidebar code. Basically reworking all the layout and a bit more.

Regarding "fonts":
I actually have no clue either right now, but according to [this](https://forum.qt.io/topic/86872/where-does-qt-get-the-default-application-font/5) it seems to be based on fontconfig after all (which I'm no expert in either...).
I for instance have "Noto Sans Regular 10" set in "appearance / font" settings (XFCE), which I guess can be considered the system wide font.
But I also added some quick debug output locally for testing purposes and it turns out that the sidebar labels are using "Cantarell" on my system.

**Comment by keybreak** [comment]
>  I actually have no clue either right now, but according to this it seems to be based on fontconfig after all (which I'm no expert in either...).

Damn, if that's the case - it's a little problem...By default (at least on Manjaro) it's some crap fonts or Deja-Vu sans at best...

I've bashed my head recently on that topic: https://forum.manjaro.org/t/kde-fonts-settings-got-ignored-by-gtk-programs/143689/39

**Comment by keybreak** [comment]
> So now with the change in 827a25b, it auto scales basically everything. Exceptiong are the first column and some columns that get even more width to make it look nicer.

Thx, looking great here! :smiley: 

>  That one isn't that easy to fix after all. I did a bit of minor resizing (3fc2625), but that's not really a fix. I guess here I missed as well that other systems with other font settings might look quite different.

Works as quickfix in my case, so thanks! But yeah...

> Looks to me that I'd basically would have to rewrite big chunks of that sidebar code. Basically reworking all the layout and a bit more.

Maybe some next time, when you'll have some free time - that would make sense, if you feel so :smiley:

**Comment by Goli4thus** [comment]
I'll keep this one open as an enhancement for some time later.

**Comment by Goli4thus** [comment]
Alright, turned out it wasn't as bad as I initially assumed after thinking it through once again.
Sidebar resizing is part of 4ae95027d13d3ffbb8e0d77a6afae8832ee9e24b.

So maybe give it a short testrun if you find the time and see if you'd consider this "enhanced" enough. ;)
If so, I guess it's about time for another release (realized the 'batch renaming' feature wasn't released either so far).

**Comment by keybreak** [comment]
Sorry for delay, tested - brilliant work again! :+1: 

Maybe it's time for cosmetic v1.0.3 release :upside_down_face:

**Comment by Goli4thus** [comment]
No problem, thanks for the feedback!
