### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by gilfuser** [Goli4thus/linvstmanager#22]
Hi!

First of all thank you for this project. It's nice to have a lighter way to manage linvst.

I*m having an error while trying to `make` the most recent version. And this is the cmake log I'm getting:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/skmecs/builds/linvstmanager/build
╭─skmecs at g in ~/builds/linvstmanager/build on master✔ 20-08-30 - 13:17:55
╰─⠠⠵ make -j 4
[  6%] Automatic MOC for target linvstmanager
[  6%] Built target linvstmanager_autogen
[  6%] Building CXX object CMakeFiles/linvstmanager.dir/src/dialogrenamebatch.cpp.o
/home/skmecs/builds/linvstmanager/src/dialogrenamebatch.cpp: In constructor ‘DialogRenameBatch::DialogRenameBatch(const QVector<VstBucket>&)’:
/home/skmecs/builds/linvstmanager/src/dialogrenamebatch.cpp:93:86: error: ‘idClicked’ is not a member of ‘QButtonGroup’
   93 | Mode, static_cast<void(QButtonGroup::*)(int)>(&QButtonGroup::idClicked), this, &DialogRenameBatch::slotModeChanged);
      |                                                              ^~~~~~~~~

/home/skmecs/builds/linvstmanager/src/dialogrenamebatch.cpp:94:90: error: ‘idClicked’ is not a member of ‘QButtonGroup’
   94 | tion, static_cast<void(QButtonGroup::*)(int)>(&QButtonGroup::idClicked), this, &DialogRenameBatch::slotLocationChanged);
      |                                                              ^~~~~~~~~

make[2]: *** [CMakeFiles/linvstmanager.dir/build.make:148: CMakeFiles/linvstmanager.dir/src/dialogrenamebatch.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/linvstmanager.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I'm on an Ubuntu Studio 20.04.

**Comment by keybreak** [comment]
@Goli4thus 
Dammit, so those changes caused regression for older than Arch system :worried:

**Comment by Goli4thus** [comment]
> Hi!
> 
> First of all thank you for this project. It's nice to have a lighter way to manage linvst.

Hi, thanks for the feedback! Always nice to hear that it's of help! :wink: 

> 
> I*m having an error while trying to `make` the most recent version. And this is the cmake log I'm getting:
>  .....
> I'm on an Ubuntu Studio 20.04.

Yeah that was not intentional.
Guess we need to be more coservative with updating to the latest APIs from now on (the curse of using an Arch based system I guess...).

I setup a new Ubuntu 20.04 VM and tracked down the actual problem.
I reverted that particular change with 3242941097f2f24aae0b375284465cf740c69190 so it uses the older API again.
Maybe you can give it another try and report back. Then I'll try to make a bugfix release.

@keybreak:
I gave it some thoughts, but I think we'll have to manage with having some warnings during build from now on.
Deprecated API usage will certainly become a bigger thing once Qt 6 becomes reality.
Maybe at some point we'll have to define a certain Qt5 version as the oldest one supported. But that will depend on how much and, above all, what Qt 6 breaks that we are using.

**Comment by keybreak** [comment]
> I gave it some thoughts, but I think we'll have to manage with having some warnings during build from now on.
Deprecated API usage will certainly become a bigger thing once Qt 6 becomes reality.
Maybe at some point we'll have to define a certain Qt5 version as the oldest one supported. But that will depend on how much and, above all, what Qt 6 breaks that we are using.

Yeah, makes sense...Better safe than sorry :+1: 
That's a burden of depending on stuff like qt, but still better like that, than else...

**Comment by gilfuser** [comment]
Cool! Now it builds.

Thanks again
