### ISSUE TITLE
Cannot Disable in Linvstmanager

### ISSUE THREAD

**Issue by klangfarben1** [Goli4thus/linvstmanager#24]
Using LinVst 3.15 and LinVSTX 3.15 and Linvstmanager 1.1.1. Currently, I can enable plugins using the E key or by right-clicking. However, I cannot disable plugins using the D key or by right clicking. Using Manjaro w Kernel 5.9.10. If I manually delete the .so file and run Linvstmanager, it does show correctly as disabled. However, if I enable it again, I cannot disable within linvstmanager.

This started happening for me the last few versions but I can't recall exactly when this started. When linvstmanager was first released, this was not an issue and disable worked fine. LinVST .so files and VST plugins are all in my home folder so there should not be any issues with permissions.

**Comment by keybreak** [comment]
Weird, i can't replicate on Manjaro, only difference i see between us in described conditions is that i use just **LinVst**...

@Goli4thus 
Perhaps it's because of simultaneous **LinVst** and **LinVstX** ?

**Comment by Goli4thus** [comment]
So I installed latest LinVst and LinVst-X (both 3.15).
But I can't reproduce it either on Manjaro.

Here's something you could try though:
1. Rebuild Linvstmanager, but instead of `cmake ..` use `cmake -DENABLE_DEBUG_MSG=1 ..`. This enables additional debug output in the terminal
2. Now run linvstmanager from terminal (you can run it already after `make` from the `build` folder using `./linvstmanager`)
3. Try to reproduce that problematic behaviour and observe if anything is being output in the terminal whenever you try to disable a VST that is "stuck on Enabled"

**Comment by Goli4thus** [comment]
@klangfarben1 
Has the issue resolved itself? Or do you still experience the problem?
