### ISSUE TITLE
[optimisation] Verification speed

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#9]
With current implementation full scan + verification of my VST folder with 2158 .dll files took:
8 minutes 36 seconds

I'm not by any means saying it's bad result, especially compared to wine checks - but i feel there might be room for optimization, perhaps some parallel processing!

**Comment by Goli4thus** [comment]
Alright, I gave it a shot: 6aab580

Let's see if you notice a difference.

EDIT: Just noticed I didn't update the build. Fixing right now. Ok, building works again (cd90cc4).

**Comment by keybreak** [comment]
Same job took:
25 seconds

I'm saying it's very good optimization :+1: 

See, i believed in you :smile: 

P.S. One thing i can think of could make it probably marginally better is changing all bash calls to POSIX sh calls, but that i guess at this point may not be necessary - 25 seconds is really good result! :smiley:

**Comment by Goli4thus** [comment]
Oh wow, didn't even think of how much of a difference it could make on stronger PCs as I only tested it on a 10 year laptop at first. And it even made a significant difference for that one.

Just tried it myself on my desktop PC. Took me approx. 20s to scan a whole wine prefix.
One could argue that the "don't scan a whole wine prefix" warning might have become a bit obsolete now.

Anyway, two more things:
1. If you compile with debug output, then there will be some information on how many threads are being used (well you can look at htop: maximum available) and the actual time it really took only the scan itself.

2. I wonder if going all out and using all threads is a good idea. On the one hand I think it's save to say that a user probably doesn't have any critical audio stuff running during a scan, because _LinVstManager_ specifically informs on startup to close any DAW.
On the other hand, putting maximum load on the system isn't really that "nice".
Even if one installs things from the _aur_ (archlinux user repo) and it has to compile the package, it won't use up all threads. 
Same as with building _LinVstManager_: One could control via `-j x` how many threads shall be used.

So maybe it would be best to only scan with `max_available - 1` or something like that, just so there's some wiggle room for other applications.

**Comment by keybreak** [comment]
> Just tried it myself on my desktop PC. Took me approx. 20s to scan a whole wine prefix.
> One could argue that the "don't scan a whole wine prefix" warning might have become a bit obsolete now.

Technically - yes outside of sanity for such scan and / or storing VSTs all over the place of course :laughing: 

> well you can look at htop: maximum available

Not sure i follow how to maximum available, but my current testing machine has CPU have 4 physical cores / 8 threads (Intel Core i7-4770K) i can also much later in time test with older Core2Duo laptop and Core i9 16 threads laptop if it means something...

But now if i filter htop by "linvstmanager" while scanning - there's maximum 8 processes running, which makes sense, it's not like all of them are 100%, pretty moderate load like 30-40% maximum on some of them.

> I wonder if going all out and using all threads is a good idea. On the one hand I think it's save to say that a user probably doesn't have any critical audio stuff running during a scan, because LinVstManager specifically informs on startup to close any DAW.

In my mind it is still very good idea, because:
a) It works REALLY good and doesn't load CPU completely at all
b) There is warning
c) I really hope that no one compiling Linux core or Wine or making 3D modeling while doing VST scan...That would be insane to count such cases, and even then i doubt it would  be problem.

> Even if one installs things from the aur (archlinux user repo) and it has to compile the package, it won't use up all threads.

Which is btw a real pain in the rear...Because it's slow (depending on complexity of build process) :laughing: 

> So maybe it would be best to only scan with max_available - 1 or something like that, just so there's some wiggle room for other applications.

I don't know...It's so supreme right now, i wouldn't want to ruin it even a little, unless there is real problem (which is really not likely from what we are seeing now) :smiley: 

Maybe best would be to see how people will use it "in the wild" and if there are some complaints would be reported about it without changing to **max_available - 1**...
Because after all, it's just ~20-25 seconds in worst case, not same thing as running something 24/7.

**Comment by Goli4thus** [comment]
![wine scan](https://i.imgur.com/5cWOgH7.png)

This is what it looks like for me doing a wine prefix scan.
So yeah, not full 100% load, but pretty high non the less.

But I guess I agree. Let's wait for real world feedback on this one and enjoy the "optimization" for a bit. ^^

**Comment by keybreak** [comment]
Wow, looks pretty loaded on your end!
Maybe it's turbo boost temporarily kickin' in or something, i have it deliberately disabled with my CPU since...well i think it's not healthy for CPU.

Let's enjoy while we can! :smiley:
